services:
  gameserver:
    image: ubuntu
    working_dir: /root
    ports:
      - 7878:7878
    restart: always
    command: ./gameserver -f conf.json
    container_name: gameserever
    volumes:
      - ./gameserver:/root/gameserver
      - ./conf/conf.json:/root/conf.json
    networks:
      - mysql_mysqlnet
      - redis_default
networks:
  mysql_mysqlnet:
    external: true
  redis_default:
    external: true
